name: Build Release Binaries

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  build:
    name: Build and Upload Release Assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Windows builds
          - os: windows
            arch: amd64
            extension: .exe
          
          # Linux builds
          - os: linux
            arch: amd64
            extension: ""
          - os: linux
            arch: arm64
            extension: ""
          - os: linux
            arch: mips64
            extension: ""
          
          # macOS builds
          - os: darwin
            arch: amd64
            extension: ""
          - os: darwin
            arch: arm64
            extension: ""

          # FreeBSD builds
          - os: freebsd
            arch: amd64
            extension: ""

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build Binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          go build -o "wssocks-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }}" cmd/wsterm/main.go

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: wssocks-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }}
